<a href="https://colab.research.google.com/github/Bronian/Python03_training_pub/blob/main/0707_01_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello World')

Hello World


In [ ]:
## numpy 샘플코드
import numpy as np

x= np.array([[1,2,3],[4,5,6]])
print ("x:\n"),x


x:



(None, array([[1, 2, 3],
        [4, 5, 6]]))

In [ ]:
x= np.array([[1,2,3],[4,5,6]])

2) SciPy 샘플 코드

In [ ]:
from scipy import sparse

# 대각선 원소는 1이고 나머지는 0인 2차원 numpy 배열을 만들어 준다
eye = np.eye(4)
print("NumPy 배열 :\n",eye)

NumPy 배열 :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
1 sparse_matrix = 
#sparse = '성긴, 밀도가 높지 않은' 이라는 의미
##미완. day01 '실습도구 소개' 문서 참조



In [ ]:
import pandas as pd

data = {'Name':["john","Anna","Peter"],
        'Location':["New York", "Paris","Berlin"],
        'age' : [24,13,53]
        }

data_pandas=pd.DataFrame(data)

#IPython.display 로 주피터 노트북에서 data frame 을 예쁘게 출력해줌
from IPython.display import display
display(data_pandas)
#print(data_pandas)        

Name  Location  age
0   john  New York   24
1   Anna     Paris   13
2  Peter    Berlin   53